apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpldapadmin
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpldapadmin
  template:
    metadata:
      labels:
        app: phpldapadmin
    spec:
      containers:
      - name: phpldapadmin
        image: osixia/phpldapadmin:latest
        env:
        - name: PHPLDAPADMIN_LDAP_HOSTS
          value: openldap
        - name: PHPLDAPADMIN_HTTPS
          value: "false"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: phpldapadmin
  namespace: devops
spec:
  selector:
    app: phpldapadmin
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
